server:
  port: 8090

spring:
  thymeleaf:
  prefix: classpath:/templates/
  suffix: .html
  mvc:
    static-path-pattern: "/static/**"

  h2:
    console:
      enabled: true

  datasource:
    hikari:
      maximum-pool-size=4:
    url: jdbc:mysql://localhost:3306/choi?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: choi
    password: 1234

  # ???? spring.io?? doc?? ??? ??????.
  # jpa??
  jpa:
    hibernate: # hibernate ?? ??
      # ?????? ?? ??? ???? ? ???, ?? ?? entity ??? ?? ?? ??? ?? ??
      # if exists drop table ??? ?? ?????? ?? ??.
      ddl-auto: update
    properties: # property ?? ??
      hibernate: # hibernate property ??
        format_sql: true

# ?? ?? ??
logging:
  level:
    # hibernate ? ??? ?? ??? debug??? ??
    # jpa hibernate? ???? sql? ??? ??? ???? ?? ??
    org.hibernate.SQL: debug
    org.hibernate.type: trace # ?? ???? ????? ???? ??